### ISSUE TITLE
Build steps

### ISSUE THREAD

**Issue by SplendornetTech** [d3ward/floatly#33]
Can you please provide the build steps? I think that portion is missing

**Comment by d3ward** [comment]
Once cloned , open the main folder in terminal. 
run `npm install` or `yarn install` to install all dependencies 
run `npm run build` or `yarn build` for building the source code and output on /dist
You can now either use load extension from the folder , or zip the content of /dist and load

Thanks , I will update the README

**Comment by SplendornetTech** [comment]
Yes thank you for the same and having it in read me will help lot of other people. Your work is surely helping me understand the the complexities that can be achieved with chrome plugin, so thank you so much for making it available. -- Thanks and RegardsAditya AchlerkarCEO, CTO,ExpandX Solutions Pvt. Ltd.www.expandx.inDirectorSplendorNet Technologies Pvt. Ltd., Pune+91 9449393235 | +1 586 806 9011 | Skype: aditya_a_a31www.SplendorNet.com    23.01.2023, 15:40, "Eduard Ursu" ***@***.***>: Once cloned , open the main folder in terminal.run npm install or yarn install to install all dependenciesrun npm run build or yarn build for building the source code and output on /distYou can now either use load extension from the folder , or zip the content of /dist and loadThanks , I will update the README—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by iLikepackagefilesnzips** [comment]
> Once cloned , open the main folder in terminal. run `npm install` or `yarn install` to install all dependencies run `npm run build` or `yarn build` for building the source code and output on /dist You can now either use load extension from the folder , or zip the content of /dist and load
> 
> Thanks , I will update the README

is this updated i honestly have no idea how to install this on laptop wiwn 10 or my pixel 5 i tried before but honestly no clue :(

**Comment by d3ward** [comment]
@iLikepackagefilesnzips still working on it . Release is expected end of month
