### ISSUE TITLE
Back Button ?

### ISSUE THREAD

**Issue by pierro78** [d3ward/floatly#4]
as said on https://discord.com/channels/494814211579445270/569541798830014471/835485145548849162 :  

great extension ! 👍 my only request would be the addition of a "back" button :wink: ... I am on the (long) xperia 5 and the nav bar (with the "back" button) doesn't seem to appear in landscape mode ... I am trying without the 3 buttons nav bar (gestures navigation mode) but my old fingers have some little difficulties to adapt :wink:

**Comment by d3ward** [comment]
This has been added in latest version v1.0.5
